//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AARP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminSetting
    {
        public int Id { get; set; }
        public int EmailTimer { get; set; }
        public string FeedbackMessage { get; set; }
        public int ReminderID { get; set; }
        public string ReminderMessage { get; set; }
    }
}
