//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AARP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int Id { get; set; }
        public int InterviewerId { get; set; }
        public int IntervieweeId { get; set; }
        public System.DateTime Date { get; set; }
        public int InterviewStageId { get; set; }
        public int SeniorityId { get; set; }
        public int TechnologyId { get; set; }
        public int StatusId { get; set; }
        public int RatingId { get; set; }
        public string InterviewerAttitude { get; set; }
        public Nullable<bool> TestTask { get; set; }
        public string TaskDifficultyLevel { get; set; }
        public Nullable<int> InterviewLengthId { get; set; }
        public string NoteFromInterviewee { get; set; }
        public string SurveyStatus { get; set; }
        public string FeedbackLink { get; set; }
    }
}
