//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AARP.Models
{
    using System;
    
    public enum ReviewStatus : int
    {
        New = 0,
        Rejected = -1,
        Accepted = 1,
        Assigned = 2,
        JobClosed = 3,
        Deleted = 4,
        HandledAsReferral = 5,
        Error = 6
    }
}
