CREATE TABLE [dbo].[AdminSettings](
	[Id] [int] NOT NULL,
	[EmailTimer] [int] NOT NULL,
	[FeedbackMessage] [ntext] NOT NULL,
	[ReminderID] [int] NOT NULL,
	[ReminderMessage] [ntext] NOT NULL,
 CONSTRAINT [PK_AdminSettings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]