CREATE TABLE [dbo].[InterviewLength](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Length] [nchar](50) NOT NULL,
 CONSTRAINT [PK_InterviewsLength] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]