CREATE TABLE [dbo].[InterviewTechnologies](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Technology] [nchar](100) NOT NULL,
 CONSTRAINT [PK_InterviewTechnologies] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]