CREATE TABLE [dbo].[Interviewees](
	[Id] [int] NOT NULL,
	[Name] [nchar](200) NOT NULL,
	[Email] [nchar](200) NULL,
	[OpeningID] [int] NOT NULL,
	[StageID] [int] NOT NULL,
 CONSTRAINT [PK_Interviewees2] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]