CREATE TABLE [dbo].[Interviewers](
	[Id] [int] NOT NULL,
	[InterviewerName] [nchar](200) NOT NULL,
	[InterviewerEmail] [nchar](200) NOT NULL,
 CONSTRAINT [PK_Interviewers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]